  
theme: jekyll-theme-minimal

# so we need to set both of these for a project?
root: /elitedangerous-notes
#baseurl: /elitedangerous-notes
url: /elitedangerous-notes

#permalink: /elitedangerous-notes/:categories/:title/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
collections:
  posts:
    output: true
    permalink: /elitedangerous-notes/:categories/:title/

