
theme: jekyll-theme-midnight
title: I blame Michael Brookes
description: My notes and reflections on some of the mysteries in Elite Dangerous

# Setting baseurl seems to work best.
#root: /elitedangerous-notes
baseurl: /elitedangerous-notes
#url: /elitedangerous-notes

author:
  name: Panzertard

# Note, images can be relative if we only use one category.
# Works with MD and relative paths. If multiple categories, relative paths will break.
# You have to make sure you have unique paths (names) for the Posts though.
collections:
  posts:
    output: true
    #permalink: /:categories/:year/:month/:day/:title:output_ext
    permalink: /:categories/:title

  systems:
    output: true
    permalink: /:categories/:title

  notes:
    output: true
    permalink: /:categories/:title

# Classify where images are and other defaults
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "systems"
    values:
      layout: "systems"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"
