  
theme: jekyll-theme-minimal

# so we need to set both of these for a project?
root: /elitedangerous-notes
#baseurl: /elitedangerous-notes
url: /elitedangerous-notes

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

