  
theme: jekyll-theme-minimal
title: Mysteries of Elite Dangerous
description: My notes and reflections on some of the mysteries in Elite Dangerous

# Setting baseurl seems to work best.
#root: /elitedangerous-notes
baseurl: /elitedangerous-notes
#url: /elitedangerous-notes

author: Panzertard

# Note, images can be relative if we only use one category.
# Works with MD and relative paths. If multiple categories, relative paths will break.  
# You have to make sure you have unique paths (names) for the Posts though.
collections:
  posts:
    output: true
    #permalink: /:categories/:year/:month/:day/:title:output_ext
    permalink: /:categories/:title:output_ext

  systems:
    output: true
    permalink: /:categories/:title
    
# Classify where images are
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      