  
theme: jekyll-theme-minimal

# so we need to set both of these for a project?
root: /elitedangerous-notes
#baseurl: /elitedangerous-notes
#url: /elitedangerous-notes

collections:
  posts:
    output: true
    permalink: /elitedangerous-notes/:categories/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true