  
theme: jekyll-theme-minimal
baseurl: /elitedangerous-notes

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
collections:
  posts:
    output: true
    permalink: /elitedangerous-notes/:categories/:year/:month/:day/:title:output_ext
    